### ISSUE TITLE
stats.xml is invalid XML

### ISSUE THREAD

**Issue by reckart** [UniversalDependencies/UD_Latin-ITTB#1]
The stats.xml file is not a valid XML file:

```
    <tag name="X">606</tag><!-- _, 4-O--------, decuplus, modus, quod, parvus, quam, vero^adv./etc. -->
```

A sequence of multiple dashes `-` may not appear in an XML comment.

Observed in UD Treebank  v 1.3.

**Comment by dan-zeman** [comment]
Fixed in dev branch.
